### PR TITLE
Fix JavaScript error

### LINKED ISSUE #1020: JavaScript exception on instrument not found page
Issue raised by: developer

### What?
JavaScript exception on instrument summary page when instrument is not found.
```js
instrument_summary.js:17
Uncaught TypeError: Cannot set property 'onchange' of null
    at init (instrument_summary.js:17)
    at instrument_summary.js:28
    at instrument_summary.js:29
```
Errors like this should be caught so that other JS code can execute on the page.

### Where?
On webapp go to `/instrument/randomstring/`
Template: `/WebApp/autoreduce_webapp/templates/instrument_summary.html`

### Reproducible?
Yes

### How to test the issue is resolved
* Load the webapp and go to `/instrument/randomstring/`, the exception should not appear in the console.

### PR DESCRIPTION
**Pull request by keiranjprice101**
### Summary of work

Check the element exists before setting onChange and onClick
Prevent automatic submission of filtering. (@dtasev I also found this confusing, and also jarring when the page would reload automatically)

### How to test your work
Verify no error on page `/runs/randomstr`
Verify no more automatic submission of filtering
Verify can still be filtered with apply

### Additional comments
 

Fixes #1020

**Before merging ensure the release notes have been updated**

### CODE REVIEW

File: WebApp/autoreduce_webapp/static/javascript/runs_list.js [hunk 1]
```diff
@@ -8,22 +8,26 @@
...
-        apply.onclick = function(){
-            setProgressCursor($(this));
+        let apply = document.getElementById('apply_filters');
+        if (apply !== null) {
+            apply.onclick = function () {
+                setProgressCursor($(this));
+            };
         }
-    };
+    }
```
Comment (rickybassom) [inline WebApp/autoreduce_webapp/static/javascript/runs_list.js:30]: I think the semicolon needs to stay because the start of this statement is `let int = ...`

**Review by rickybassom — CHANGES_REQUESTED** [review]
Works well 👍

File: WebApp/autoreduce_webapp/static/javascript/runs_list.js (hunk 1 above)
Comment (keiranjprice101) [reply WebApp/autoreduce_webapp/static/javascript/runs_list.js]: My mistake

**Review by rickybassom — APPROVED** [review]
